ports:
  websecure:
    http3:
      enabled: false
persistence:
  enabled: true
  storageClass: openebs-hostpath
certResolvers:
  letsencrypt:
    email: alex@alexanderme.com
    dnsChallenge:
      provider: cloudflare
      resolvers:
        - 1.1.1.1
        - 9.9.9.9
    storage: /data/acme.json
env:
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare
        key: apitoken
deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:latest
      command: ["sh", "-c", "touch /data/acme.json && chmod -v 600 /data/acme.json"]
      volumeMounts:
        - name: data
          mountPath: /data
