ports:
  websecure:
    http3:
      enabled: true
ingressRoute:
  dashboard:
    # -- Create an IngressRoute for the dashboard
    enabled: true
    matchRule: Host('traefik.azollerstuff.xyz')
    # -- Specify the allowed entrypoints to use for the dashboard ingress route, (e.g. traefik, web, websecure).
    # By default, it's using traefik entrypoint, which is not exposed.
    # /!\ Do not expose your dashboard without any protection over the internet /!\
    entryPoints: ["websecure"]
    services:
    - name: traefikweb
      port: 9000
    # -- Additional ingressRoute middlewares (e.g. for authentication)
    middlewares: ["headers"]
    tls:
      certResolver: letsencrypt
      domains:
      - main: azollerstuff.xyz
        sans:
        - '*.azollerstuff.xyz'
additionalArguments:
  - "--providers.consulcatalog=true"
  - "--providers.consulcatalog.exposedByDefault=false"
  - "--providers.consulCatalog.endpoint.address=192.168.1.5"
  - "--providers.consulCatalog.endpoint.scheme=http"
persistence:
  enabled: true
  storageClass: local-path
certResolvers:
  letsencrypt:
    email: alex@alexanderme.com
    dnsChallenge:
      provider: cloudflare
      resolvers:
        - 1.1.1.1
        - 9.9.9.9
    storage: /data/acme.json
env:
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflarekey
        key: cfk
deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:latest
      command: ["sh", "-c", "touch /data/acme.json && chmod -v 600 /data/acme.json"]
      volumeMounts:
        - name: data
          mountPath: /data
