ports:
  websecure:
    http3:
      enabled: true
ingressRoute:
  dashboard:
    # -- Create an IngressRoute for the dashboard
    enabled: true
    matchRule: Host('traefik.azollerstuff.xyz')
    entryPoints: ["websecure"]
    middlewares:
      - name: traefik-dashboard-auth
extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: traefik-dashboard-auth-secret
    type: kubernetes.io/basic-auth
    stringData:
      username: admin
      password: ezpassword

  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: traefik-dashboard-auth
    spec:
      basicAuth:
        secret: traefik-dashboard-auth-secret

additionalArguments:
  - "--providers.consulcatalog=true"
  - "--providers.consulcatalog.exposedByDefault=false"
  - "--providers.consulCatalog.endpoint.address=192.168.1.5"
  - "--providers.consulCatalog.endpoint.scheme=http"
persistence:
  enabled: true
  storageClass: local-path
certResolvers:
  letsencrypt:
    email: alex@alexanderme.com
    dnsChallenge:
      provider: cloudflare
      resolvers:
        - 1.1.1.1
        - 9.9.9.9
    storage: /data/acme.json
env:
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflarekey
        key: cfk
deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:latest
      command: ["sh", "-c", "touch /data/acme.json && chmod -v 600 /data/acme.json"]
      volumeMounts:
        - name: data
          mountPath: /data
