apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: default
spec:
  provider:
    vault:
      server: "http://192.168.1.3:8200"
      path: "kv"
      version: "v2"
      auth:
        appRole:
          path: "approle"
          roleId: "32713311-8820-77bb-02ef-824afbef4bdd"
          secretRef:
            name: "kube-approle-secret"
            key: "secret-id"
