apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-pvc
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: seaweedfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
