apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: actual
spec:
  entryPoints:
    - websecure
  routes:
  - match:
    valueFrom:
     configMapKeyRef:
       name: traefik-host-domain
       key: actual
    kind: Rule
    services:
    - name: actual
      port: 5006
  tls:
    certResolver: letsencrypt
