
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-server-data
  namespace: default
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
