apiVersion: apps/v1
kind: Deployment
metadata:
  name: myspotify
  namespace: default
  labels:
    app: myspotify
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: myspotify
  template:
    metadata:
      labels:
        app: myspotify
    spec:
      containers:
      - name: myspotify-server
        image: yooooomi/your_spotify_server:latest
        ports:
        - containerPort: 8080
          name: server
        env:
        - name: TIMEZONE
          value: "America/Chicago"
        - name: MONGO_ENDPOINT
          value: "mongodb://localhost:27017/your_spotify"
        envFrom:
        - secretRef:
            name: myspotify-secrets-new
      - name: myspotify-web
        image: yooooomi/your_spotify_client:latest
        ports:
        - containerPort: 3000
          name: web
        env:
        - name: MONGO_ENDPOINT
          value: "mongodb://localhost:27017/your_spotify"
        - name: API_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: myspotify-secrets-new
              key: API_ENDPOINT
      - name: mongo
        image: mongo:6.0
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data
        ports:
        - containerPort: 27071
          name: mongo
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: myspotify-pvc
