apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: myspotify-secrets
spec:
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: myspotify-secrets
  dataFrom:
  - extract:
      key: /kube/myspotify/env
