apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: myspotify-secrets-new
spec:
  secretStoreRef:
    name: vault-backend-new
    kind: SecretStore
  target:
    name: myspotify-secrets-new
  dataFrom:
  - extract:
      key: /kube/myspotify/env
