apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myspotify-mongo-data
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: juicefs-sc-myspotify
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
