apiVersion: v1
kind: PersistentVolume
metadata:
  name: juicefs-myspotify-pv
  labels:
    juicefs-name: myspotify-pv
spec:
  mountOptions:
    - subdir=/juicefs-myspotify-mongo
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: csi.juicefs.com
    volumeHandle: juicefs-myspotify-pv
    fsType: juicefs
    nodePublishSecretRef:
      name: juicefs-myspotify
      namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juicefs-myspotify-pvc
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      juicefs-name: myspotify-pv
