apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-obsid-pvc
  namespace: default
  labels:
    app: couchdb-obsid
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
#    argocd.argoproj.io/sync-wave: "1"
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
