apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: couchdb-obsid-secrets
spec:
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: couchdb-obsid-secrets
  dataFrom:
  - extract:
      key: /kube/couchdb/env
