apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actual
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/actual-budgets
    repoURL: https://github.com/azoller1/k3s-infra.git
    targetRevision: main
