apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gotify
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
    - ApplyOutOfSyncOnly=true
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/gotify
    repoURL: https://github.com/azoller1/k3s-infra.git
    targetRevision: main
