apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: juicefs
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  project: default
  sources:
  - chart: juicefs-csi-driver
    repoURL: https://juicedata.github.io/charts/
    targetRevision: 0.19.2
    helm:
      releaseName: juicefs-csi-driver
  destination:
    server: https://kubernetes.default.svc
    namespace: juicefs
